# netlify.toml

[build]
  # Your build command and publish directory (usually set automatically for Next.js)
    command = "npm run build"
    publish = ".next"

[functions.timeout]
  # Set the default timeout for all functions to 26 seconds
  timeout = 400 # Maximum allowed on Pro plan. Set to 10 on Free plan if you explicitly need it.
